docs(quickstart): add missing config in get_parameters
This fixes the:

```
TypeError: MNISTClient.get_parameters() got an unexpected keyword argument 'config'
```

seen when running the MNIST client.